### PR TITLE
Add db tasks for better collaboration

### LINKED ISSUE #8: Add db tasks for better collaboration
It should be possible to import and export databases using default db tasks

### PR DESCRIPTION
**Pull request by slashplusweb**
closes #8

### CODE REVIEW

**Comment by bambamboole** [comment]
can you please remove the whole gzip and mysql quick load stuff.

**Comment by slashplusweb** [comment]
> can you please remove the whole gzip and mysql quick load stuff. As these databases are quite small it is a bigger benefit to be able to look into the dumps than have them smaller.

done

**Comment by bambamboole** [comment]
The web path is still in and not used. If you remove it, this gets merged.

**Comment by slashplusweb** [comment]
> The web path is still in and not used. If you remove it, this gets merged.

done

**Pull request merged**
